# keymap_drawer.config.yaml

parse_config:
  zmk_remove_keycode_prefix: ["RU_","RU_CYRILLIC_"]  # strip prefixes like RU_ or EN_ if needed
  zmk_additional_includes: []    # extra include paths, if your .keymap uses modules

draw_config:
  svg_extra_style: |
    /* Example: make layer names slightly bigger */
    text.layer-name { font-size: 1.15em; }
  style_layer_activators: true  # underline activators
